In [1]:
suppressPackageStartupMessages({
    library(dplyr)
    library(stringr)
    library(Biostrings)
    library(data.table)
    library(igraph)
    library(pwalign)
    library(Rsamtools)
    library(parallel)
})

source("/srv/home/mlef0011/VDARK/src/utils.r")

WD       <- "/srv/home/mlef0011/VDARK"
MINIMAP  <- "/srv/home/mlef0011/anaconda3/envs/VDARK/bin/minimap2"
REF      <- "/srv/home/mlef0011/rawdata/ref_genome/reference_genome_GRCh37.fa"
N_CORES  <- max(1, detectCores() - 1)

### Load data

In [2]:

load_reads <- function(r1, r2) {
    fq1 <- readDNAStringSet(r1, format = "fastq")
    fq2 <- readDNAStringSet(r2, format = "fastq")
    data.frame(
        read_ID  = c(names(fq1), names(fq2)),
        sequence = as.character(c(fq1, fq2)),
        stringsAsFactors = FALSE
    )
}

tumour_reads <- load_reads(
    file.path(WD, "rawdata/reads/tumour_R1_tumour_specific.fq"),
    file.path(WD, "rawdata/reads/tumour_R2_tumour_specific.fq")
)

### Associate each k-mer with its original read.

In [3]:
system("/srv/home/mlef0011/anaconda3/condabin/conda run -n VDARK python3 /srv/home/mlef0011/VDARK/src/build_read_kmer_table.py")

### Clustering reads sharing same k-mers to perfom local assembly

In [6]:
read_kmer_df <- fread(file.path(WD, "rawdata/reads/read_kmer_association.tsv"))
read_kmer_df <- read_kmer_df[, if (.N <= 50) .SD, by = kmer]   # drop high-freq k-mers

pairs <- read_kmer_df[, {
    ids <- read_ID
    if (length(ids) >= 2) {
        idx <- combn(length(ids), 2)
        data.table(read_ID.x = ids[idx[1,]], read_ID.y = ids[idx[2,]])
    }
}, by = kmer][, .(weight = .N), by = .(read_ID.x, read_ID.y)]

G <- graph_from_data_frame(pairs, directed = FALSE)
E(G)$weight <- pairs$weight
clusters <- components(G)
cat(clusters$no, " clusters")

3235  clusters

In [27]:
cluster_ID = 10

### Construct tumor contig

In [28]:
reads_in  <- names(clusters$membership)[clusters$membership == cluster_ID]
kmers_sig <- unique(read_kmer_df$kmer[read_kmer_df$read_ID %in% reads_in])
all_kmers <- unique(unlist(lapply(
    tumour_reads$sequence[tumour_reads$read_ID %in% reads_in], get_kmers
)))

cat("  ", length(reads_in), " reads | ", length(kmers_sig), " specific k-mers")

contig_tumour <- assemble_kmers(kmers_sig, k = K)
cat("  Tumour contig: ", nchar(contig_tumour[1]), " bp")
contig_tumour

   6522  reads |  4482  specific k-mers  Tumour contig:  72  bp

[1] "GATCGGAAGAGCACAACGTCTGAACTCCAGTCACAATGTTCTATCACGTATGCCGTCTTCTGCTTGAAAAAA"
[2] "TTTTTTCAAGCAGAAGACGGCATACGTGATAGAACATTGTGACTGGAGTTCAGACGTTGTGCTCTTCCGATC"

In [29]:
flanking_kmers <- setdiff(all_kmers, kmers_sig)
flanking_fa    <- file.path(WD, "tmp", paste0("flanking_", cluster_ID, ".fa"))
kmc_db         <- file.path(WD, "tmp", paste0("flanking_kmc_", cluster_ID))

writeLines(paste0(">k_", seq_along(flanking_kmers), "\n", flanking_kmers), flanking_fa)

system(paste(KMC, "-k31 -t12 -ci1 -fm", flanking_fa, kmc_db, file.path(WD, "tmp")),
       ignore.stdout = TRUE, ignore.stderr = TRUE)



fq_R1_out <- file.path(WD, "tmp", paste0("normal_R1_locus_", cluster_ID, ".fq"))
fq_R2_out <- file.path(WD, "tmp", paste0("normal_R2_locus_", cluster_ID, ".fq"))

NORMAL_R1 = file.path(WD,"rawdata/reads/normal_R1.fq")
NORMAL_R2 = file.path(WD,"rawdata/reads/normal_R2.fq")

system(paste(KMC_TOOLS, "filter", kmc_db, "-ci1", NORMAL_R1, fq_R1_out),
       ignore.stdout = TRUE, ignore.stderr = TRUE)
system(paste(KMC_TOOLS, "filter", kmc_db, "-ci1", NORMAL_R2, fq_R2_out),
       ignore.stdout = TRUE, ignore.stderr = TRUE)

normal_df <- tryCatch(
    load_reads(fq_R1_out, fq_R2_out),
    error = function(e) data.frame(read_ID = character(), sequence = character())
)

In [34]:
flanking_kmers <- flanking_kmers[grepl("^[ACGT]+$", flanking_kmers)]

pdict  <- PDict(unique(c(flanking_kmers,
                                 as.character(reverseComplement(DNAStringSet(flanking_kmers))))))

In [35]:
seq_len(clusters$no)

   [1]    1    2    3    4    5    6    7    8    9   10   11   12   13   14
  [15]   15   16   17   18   19   20   21   22   23   24   25   26   27   28
  [29]   29   30   31   32   33   34   35   36   37   38   39   40   41   42
  [43]   43   44   45   46   47   48   49   50   51   52   53   54   55   56
  [57]   57   58   59   60   61   62   63   64   65   66   67   68   69   70
  [71]   71   72   73   74   75   76   77   78   79   80   81   82   83   84
  [85]   85   86   87   88   89   90   91   92   93   94   95   96   97   98
  [99]   99  100  101  102  103  104  105  106  107  108  109  110  111  112
 [113]  113  114  115  116  117  118  119  120  121  122  123  124  125  126
 [127]  127  128  129  130  131  132  133  134  135  136  137  138  139  140
 [141]  141  142  143  144  145  146  147  148  149  150  151  152  153  154
 [155]  155  156  157  158  159  160  161  162  163  164  165  166  167  168
 [169]  169  170  171  172  173  174  175  176  177  178  179  180  181  182
 [183]  183  184  185  186  187  188  189  190  191  192  193  194  195  196
 [197]  197  198  199  200  201  202  203  204  205  206  207  208  209  210
 [211]  211  212  213  214  215  216  217  218  219  220  221  222  223  224
 [225]  225  226  227  228  229  230  231  232  233  234  235  236  237  238
 [239]  239  240  241  242  243  244  245  246  247  248  249  250  251  252
 [253]  253  254  255  256  257  258  259  260  261  262  263  264  265  266
 [267]  267  268  269  270  271  272  273  274  275  276  277  278  279  280
 [281]  281  282  283  284  285  286  287  288  289  290  291  292  293  294
 [295]  295  296  297  298  299  300  301  302  303  304  305  306  307  308
 [309]  309  310  311  312  313  314  315  316  317  318  319  320  321  322
 [323]  323  324  325  326  327  328  329  330  331  332  333  334  335  336
 [337]  337  338  339  340  341  342  343  344  345  346  347  348  349  350
 [351]  351  352  353  354  355  356  357  358  359  360  361  362  363  364
 [365]  365  366  367  368  369  370  371  372  373  374  375  376  377  378
 [379]  379  380  381  382  383  384  385  386  387  388  389  390  391  392
 [393]  393  394  395  396  397  398  399  400  401  402  403  404  405  406
 [407]  407  408  409  410  411  412  413  414  415  416  417  418  419  420
 [421]  421  422  423  424  425  426  427  428  429  430  431  432  433  434
 [435]  435  436  437  438  439  440  441  442  443  444  445  446  447  448
 [449]  449  450  451  452  453  454  455  456  457  458  459  460  461  462
 [463]  463  464  465  466  467  468  469  470  471  472  473  474  475  476
 [477]  477  478  479  480  481  482  483  484  485  486  487  488  489  490
 [491]  491  492  493  494  495  496  497  498  499  500  501  502  503  504
 [505]  505  506  507  508  509  510  511  512  513  514  515  516  517  518
 [519]  519  520  521  522  523  524  525  526  527  528  529  530  531  532
 [533]  533  534  535  536  537  538  539  540  541  542  543  544  545  546
 [547]  547  548  549  550  551  552  553  554  555  556  557  558  559  560
 [561]  561  562  563  564  565  566  567  568  569  570  571  572  573  574
 [575]  575  576  577  578  579  580  581  582  583  584  585  586  587  588
 [589]  589  590  591  592  593  594  595  596  597  598  599  600  601  602
 [603]  603  604  605  606  607  608  609  610  611  612  613  614  615  616
 [617]  617  618  619  620  621  622  623  624  625  626  627  628  629  630
 [631]  631  632  633  634  635  636  637  638  639  640  641  642  643  644
 [645]  645  646  647  648  649  650  651  652  653  654  655  656  657  658
 [659]  659  660  661  662  663  664  665  666  667  668  669  670  671  672
 [673]  673  674  675  676  677  678  679  680  681  682  683  684  685  686
 [687]  687  688  689  690  691  692  693  694  695  696  697  698  699  700
 [701]  701  702  703  704  705  706  707  708  709  710  711  712  713  714
 [715]  715  716  717  718  719  720  721  722  723  724  725  726  727  728
 [729]  729  730  731  732  733  734  735  736  737  738  739  740  741  742
 [743]  743  744  745  746  747  748  749  750  751  752  753  754  755  756
 [757]  757  758  759  760  761  762  763  764  765  766  767  768  769  770
 [771]  771  772  773  774  775  776  777  778  779  780  781  782  783  784
 [785]  785  786  787  788  789  790  791  792  793  794  795  796  797  798
 [799]  799  800  801  802  803  804  805  806  807  808  809  810  811  812
 [813]  813  814  815  816  817  818  819  820  821  822  823  824  825  826
 [827]  827  828  829  830  831  832  833  834  835  836  837  838  839  840
 [841]  841  842  843  844  845  846  847  848  849  850  851  852  853  854
 [855]  855  856  857  858  859  860  861  862  863  864  865  866  867  868
 [869]  869  870  871  872  873  874  875  876  877  878  879  880  881  882
 [883]  883  884  885  886  887  888  889  890  891  892  893  894  895  896
 [897]  897  898  899  900  901  902  903  904  905  906  907  908  909  910
 [911]  911  912  913  914  915  916  917  918  919  920  921  922  923  924
 [925]  925  926  927  928  929  930  931  932  933  934  935  936  937  938
 [939]  939  940  941  942  943  944  945  946  947  948  949  950  951  952
 [953]  953  954  955  956  957  958  959  960  961  962  963  964  965  966
 [967]  967  968  969  970  971  972  973  974  975  976  977  978  979  980
 [981]  981  982  983  984  985  986  987  988  989  990  991  992  993  994
 [995]  995  996  997  998  999 1000 1001 1002 1003 1004 1005 1006 1007 1008
[1009] 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022
[1023] 1023 1024 1025 1026 1027 1028 1029 1030 1031 1032 1033 1034 1035 1036
[1037] 1037 1038 1039 1040 1041 1042 1043 1044 1045 1046 1047 1048 1049 1050
[1051] 1051 1052 1053 1054 1055 1056 1057 1058 1059 1060 1061 1062 1063 1064
[1065] 1065 1066 1067 1068 1069 1070 1071 1072 1073 1074 1075 1076 1077 1078
[1079] 1079 1080 1081 1082 1083 1084 1085 1086 1087 1088 1089 1090 1091 1092
[1093] 1093 1094 1095 1096 1097 1098 1099 1100 1101 1102 1103 1104 1105 1106
[1107] 1107 1108 1109 1110 1111 1112 1113 1114 1115 1116 1117 1118 1119 1120
[1121] 1121 1122 1123 1124 1125 1126 1127 1128 1129 1130 1131 1132 1133 1134
[1135] 1135 1136 1137 1138 1139 1140 1141 1142 1143 1144 1145 1146 1147 1148
[1149] 1149 1150 1151 1152 1153 1154 1155 1156 1157 1158 1159 1160 1161 1162
[1163] 1163 1164 1165 1166 1167 1168 1169 1170 1171 1172 1173 1174 1175 1176
[1177] 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190
[1191] 1191 1192 1193 1194 1195 1196 1197 1198 1199 1200 1201 1202 1203 1204
[1205] 1205 1206 1207 1208 1209 1210 1211 1212 1213 1214 1215 1216 1217 1218
[1219] 1219 1220 1221 1222 1223 1224 1225 1226 1227 1228 1229 1230 1231 1232
[1233] 1233 1234 1235 1236 1237 1238 1239 1240 1241 1242 1243 1244 1245 1246
[1247] 1247 1248 1249 1250 1251 1252 1253 1254 1255 1256 1257 1258 1259 1260
[1261] 1261 1262 1263 1264 1265 1266 1267 1268 1269 1270 1271 1272 1273 1274
[1275] 1275 1276 1277 1278 1279 1280 1281 1282 1283 1284 1285 1286 1287 1288
[1289] 1289 1290 1291 1292 1293 1294 1295 1296 1297 1298 1299 1300 1301 1302
[1303] 1303 1304 1305 1306 1307 1308 1309 1310 1311 1312 1313 1314 1315 1316
[1317] 1317 1318 1319 1320 1321 1322 1323 1324 1325 1326 1327 1328 1329 1330
[1331] 1331 1332 1333 1334 1335 1336 1337 1338 1339 1340 1341 1342 1343 1344
[1345] 1345 1346 1347 1348 1349 1350 1351 1352 1353 1354 1355 1356 1357 1358
[1359] 1359 1360 1361 1362 1363 1364 1365 1366 1367 1368 1369 1370 1371 1372
[1373] 1373 1374 1375 1376 1377 1378 1379 1380 1381 1382 1383 1384 1385 1386
[1387] 1387 1388 1389 1390 1391 1392 1393 1394 1395 1396 1397 1398 1399 1400
[1401] 1401 1402 1403 1404 1405 1406 1407 1408 1409 1410 1411 1412 1413 1414
[1415] 1415 1416 1417 1418 1419 1420 1421 1422 1423 1424 1425 1426 1427 1428
[1429] 1429 1430 1431 1432 1433 1434 1435 1436 1437 1438 1439 1440 1441 1442
[1443] 1443 1444 1445 1446 1447 1448 1449 1450 1451 1452 1453 1454 1455 1456
[1457] 1457 1458 1459 1460 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470
[1471] 1471 1472 1473 1474 1475 1476 1477 1478 1479 1480 1481 1482 1483 1484
[1485] 1485 1486 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498
[1499] 1499 1500 1501 1502 1503 1504 1505 1506 1507 1508 1509 1510 1511 1512
[1513] 1513 1514 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526
[1527] 1527 1528 1529 1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 1540
[1541] 1541 1542 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554
[1555] 1555 1556 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568
[1569] 1569 1570 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580 1581 1582
[1583] 1583 1584 1585 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596
[1597] 1597 1598 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610
[1611] 1611 1612 1613 1614 1615 1616 1617 1618 1619 1620 1621 1622 1623 1624
[1625] 1625 1626 1627 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638
[1639] 1639 1640 1641 1642 1643 1644 1645 1646 1647 1648 1649 1650 1651 1652
[1653] 1653 1654 1655 1656 1657 1658 1659 1660 1661 1662 1663 1664 1665 1666
[1667] 1667 1668 1669 1670 1671 1672 1673 1674 1675 1676 1677 1678 1679 1680
[1681] 1681 1682 1683 1684 1685 1686 1687 1688 1689 1690 1691 1692 1693 1694
[1695] 1695 1696 1697 1698 1699 1700 1701 1702 1703 1704 1705 1706 1707 1708
[1709] 1709 1710 1711 1712 1713 1714 1715 1716 1717 1718 1719 1720 1721 1722
[1723] 1723 1724 1725 1726 1727 1728 1729 1730 1731 1732 1733 1734 1735 1736
[1737] 1737 1738 1739 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750
[1751] 1751 1752 1753 1754 1755 1756 1757 1758 1759 1760 1761 1762 1763 1764
[1765] 1765 1766 1767 1768 1769 1770 1771 1772 1773 1774 1775 1776 1777 1778
[1779] 1779 1780 1781 1782 1783 1784 1785 1786 1787 1788 1789 1790 1791 1792
[1793] 1793 1794 1795 1796 1797 1798 1799 1800 1801 1802 1803 1804 1805 1806
[1807] 1807 1808 1809 1810 1811 1812 1813 1814 1815 1816 1817 1818 1819 1820
[1821] 1821 1822 1823 1824 1825 1826 1827 1828 1829 1830 1831 1832 1833 1834
[1835] 1835 1836 1837 1838 1839 1840 1841 1842 1843 1844 1845 1846 1847 1848
[1849] 1849 1850 1851 1852 1853 1854 1855 1856 1857 1858 1859 1860 1861 1862
[1863] 1863 1864 1865 1866 1867 1868 1869 1870 1871 1872 1873 1874 1875 1876
[1877] 1877 1878 1879 1880 1881 1882 1883 1884 1885 1886 1887 1888 1889 1890
[1891] 1891 1892 1893 1894 1895 1896 1897 1898 1899 1900 1901 1902 1903 1904
[1905] 1905 1906 1907 1908 1909 1910 1911 1912 1913 1914 1915 1916 1917 1918
[1919] 1919 1920 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932
[1933] 1933 1934 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946
[1947] 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960
[1961] 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974
[1975] 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988
[1989] 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002
[2003] 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016
[2017] 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028 2029 2030
[2031] 2031 2032 2033 2034 2035 2036 2037 2038 2039 2040 2041 2042 2043 2044
[2045] 2045 2046 2047 2048 2049 2050 2051 2052 2053 2054 2055 2056 2057 2058
[2059] 2059 2060 2061 2062 2063 2064 2065 2066 2067 2068 2069 2070 2071 2072
[2073] 2073 2074 2075 2076 2077 2078 2079 2080 2081 2082 2083 2084 2085 2086
[2087] 2087 2088 2089 2090 2091 2092 2093 2094 2095 2096 2097 2098 2099 2100
[2101] 2101 2102 2103 2104 2105 2106 2107 2108 2109 2110 2111 2112 2113 2114
[2115] 2115 2116 2117 2118 2119 2120 2121 2122 2123 2124 2125 2126 2127 2128
[2129] 2129 2130 2131 2132 2133 2134 2135 2136 2137 2138 2139 2140 2141 2142
[2143] 2143 2144 2145 2146 2147 2148 2149 2150 2151 2152 2153 2154 2155 2156
[2157] 2157 2158 2159 2160 2161 2162 2163 2164 2165 2166 2167 2168 2169 2170
[2171] 2171 2172 2173 2174 2175 2176 2177 2178 2179 2180 2181 2182 2183 2184
[2185] 2185 2186 2187 2188 2189 2190 2191 2192 2193 2194 2195 2196 2197 2198
[2199] 2199 2200 2201 2202 2203 2204 2205 2206 2207 2208 2209 2210 2211 2212
[2213] 2213 2214 2215 2216 2217 2218 2219 2220 2221 2222 2223 2224 2225 2226
[2227] 2227 2228 2229 2230 2231 2232 2233 2234 2235 2236 2237 2238 2239 2240
[2241] 2241 2242 2243 2244 2245 2246 2247 2248 2249 2250 2251 2252 2253 2254
[2255] 2255 2256 2257 2258 2259 2260 2261 2262 2263 2264 2265 2266 2267 2268
[2269] 2269 2270 2271 2272 2273 2274 2275 2276 2277 2278 2279 2280 2281 2282
[2283] 2283 2284 2285 2286 2287 2288 2289 2290 2291 2292 2293 2294 2295 2296
[2297] 2297 2298 2299 2300 2301 2302 2303 2304 2305 2306 2307 2308 2309 2310
[2311] 2311 2312 2313 2314 2315 2316 2317 2318 2319 2320 2321 2322 2323 2324
[2325] 2325 2326 2327 2328 2329 2330 2331 2332 2333 2334 2335 2336 2337 2338
[2339] 2339 2340 2341 2342 2343 2344 2345 2346 2347 2348 2349 2350 2351 2352
[2353] 2353 2354 2355 2356 2357 2358 2359 2360 2361 2362 2363 2364 2365 2366
[2367] 2367 2368 2369 2370 2371 2372 2373 2374 2375 2376 2377 2378 2379 2380
[2381] 2381 2382 2383 2384 2385 2386 2387 2388 2389 2390 2391 2392 2393 2394
[2395] 2395 2396 2397 2398 2399 2400 2401 2402 2403 2404 2405 2406 2407 2408
[2409] 2409 2410 2411 2412 2413 2414 2415 2416 2417 2418 2419 2420 2421 2422
[2423] 2423 2424 2425 2426 2427 2428 2429 2430 2431 2432 2433 2434 2435 2436
[2437] 2437 2438 2439 2440 2441 2442 2443 2444 2445 2446 2447 2448 2449 2450
[2451] 2451 2452 2453 2454 2455 2456 2457 2458 2459 2460 2461 2462 2463 2464
[2465] 2465 2466 2467 2468 2469 2470 2471 2472 2473 2474 2475 2476 2477 2478
[2479] 2479 2480 2481 2482 2483 2484 2485 2486 2487 2488 2489 2490 2491 2492
[2493] 2493 2494 2495 2496 2497 2498 2499 2500 2501 2502 2503 2504 2505 2506
[2507] 2507 2508 2509 2510 2511 2512 2513 2514 2515 2516 2517 2518 2519 2520
[2521] 2521 2522 2523 2524 2525 2526 2527 2528 2529 2530 2531 2532 2533 2534
[2535] 2535 2536 2537 2538 2539 2540 2541 2542 2543 2544 2545 2546 2547 2548
[2549] 2549 2550 2551 2552 2553 2554 2555 2556 2557 2558 2559 2560 2561 2562
[2563] 2563 2564 2565 2566 2567 2568 2569 2570 2571 2572 2573 2574 2575 2576
[2577] 2577 2578 2579 2580 2581 2582 2583 2584 2585 2586 2587 2588 2589 2590
[2591] 2591 2592 2593 2594 2595 2596 2597 2598 2599 2600 2601 2602 2603 2604
[2605] 2605 2606 2607 2608 2609 2610 2611 2612 2613 2614 2615 2616 2617 2618
[2619] 2619 2620 2621 2622 2623 2624 2625 2626 2627 2628 2629 2630 2631 2632
[2633] 2633 2634 2635 2636 2637 2638 2639 2640 2641 2642 2643 2644 2645 2646
[2647] 2647 2648 2649 2650 2651 2652 2653 2654 2655 2656 2657 2658 2659 2660
[2661] 2661 2662 2663 2664 2665 2666 2667 2668 2669 2670 2671 2672 2673 2674
[2675] 2675 2676 2677 2678 2679 2680 2681 2682 2683 2684 2685 2686 2687 2688
[2689] 2689 2690 2691 2692 2693 2694 2695 2696 2697 2698 2699 2700 2701 2702
[2703] 2703 2704 2705 2706 2707 2708 2709 2710 2711 2712 2713 2714 2715 2716
[2717] 2717 2718 2719 2720 2721 2722 2723 2724 2725 2726 2727 2728 2729 2730
[2731] 2731 2732 2733 2734 2735 2736 2737 2738 2739 2740 2741 2742 2743 2744
[2745] 2745 2746 2747 2748 2749 2750 2751 2752 2753 2754 2755 2756 2757 2758
[2759] 2759 2760 2761 2762 2763 2764 2765 2766 2767 2768 2769 2770 2771 2772
[2773] 2773 2774 2775 2776 2777 2778 2779 2780 2781 2782 2783 2784 2785 2786
[2787] 2787 2788 2789 2790 2791 2792 2793 2794 2795 2796 2797 2798 2799 2800
[2801] 2801 2802 2803 2804 2805 2806 2807 2808 2809 2810 2811 2812 2813 2814
[2815] 2815 2816 2817 2818 2819 2820 2821 2822 2823 2824 2825 2826 2827 2828
[2829] 2829 2830 2831 2832 2833 2834 2835 2836 2837 2838 2839 2840 2841 2842
[2843] 2843 2844 2845 2846 2847 2848 2849 2850 2851 2852 2853 2854 2855 2856
[2857] 2857 2858 2859 2860 2861 2862 2863 2864 2865 2866 2867 2868 2869 2870
[2871] 2871 2872 2873 2874 2875 2876 2877 2878 2879 2880 2881 2882 2883 2884
[2885] 2885 2886 2887 2888 2889 2890 2891 2892 2893 2894 2895 2896 2897 2898
[2899] 2899 2900 2901 2902 2903 2904 2905 2906 2907 2908 2909 2910 2911 2912
[2913] 2913 2914 2915 2916 2917 2918 2919 2920 2921 2922 2923 2924 2925 2926
[2927] 2927 2928 2929 2930 2931 2932 2933 2934 2935 2936 2937 2938 2939 2940
[2941] 2941 2942 2943 2944 2945 2946 2947 2948 2949 2950 2951 2952 2953 2954
[2955] 2955 2956 2957 2958 2959 2960 2961 2962 2963 2964 2965 2966 2967 2968
[2969] 2969 2970 2971 2972 2973 2974 2975 2976 2977 2978 2979 2980 2981 2982
[2983] 2983 2984 2985 2986 2987 2988 2989 2990 2991 2992 2993 2994 2995 2996
[2997] 2997 2998 2999 3000 3001 3002 3003 3004 3005 3006 3007 3008 3009 3010
[3011] 3011 3012 3013 3014 3015 3016 3017 3018 3019 3020 3021 3022 3023 3024
[3025] 3025 3026 3027 3028 3029 3030 3031 3032 3033 3034 3035 3036 3037 3038
[3039] 3039 3040 3041 3042 3043 3044 3045 3046 3047 3048 3049 3050 3051 3052
[3053] 3053 3054 3055 3056 3057 3058 3059 3060 3061 3062 3063 3064 3065 3066
[3067] 3067 3068 3069 3070 3071 3072 3073 3074 3075 3076 3077 3078 3079 3080
[3081] 3081 3082 3083 3084 3085 3086 3087 3088 3089 3090 3091 3092 3093 3094
[3095] 3095 3096 3097 3098 3099 3100 3101 3102 3103 3104 3105 3106 3107 3108
[3109] 3109 3110 3111 3112 3113 3114 3115 3116 3117 3118 3119 3120 3121 3122
[3123] 3123 3124 3125 3126 3127 3128 3129 3130 3131 3132 3133 3134 3135 3136
[3137] 3137 3138 3139 3140 3141 3142 3143 3144 3145 3146 3147 3148 3149 3150
[3151] 3151 3152 3153 3154 3155 3156 3157 3158 3159 3160 3161 3162 3163 3164
[3165] 3165 3166 3167 3168 3169 3170 3171 3172 3173 3174 3175 3176 3177 3178
[3179] 3179 3180 3181 3182 3183 3184 3185 3186 3187 3188 3189 3190 3191 3192
[3193] 3193 3194 3195 3196 3197 3198 3199 3200 3201 3202 3203 3204 3205 3206
[3207] 3207 3208 3209 3210 3211 3212 3213 3214 3215 3216 3217 3218 3219 3220
[3221] 3221 3222 3223 3224 3225 3226 3227 3228 3229 3230 3231 3232 3233 3234
[3235] 3235

In [31]:
 # Precise filtering: keep reads with ≥ 30 flanking k-mer hits
    if (nrow(normal_df) > 0) {
        pdict  <- PDict(unique(c(flanking_kmers,
                                 as.character(reverseComplement(DNAStringSet(flanking_kmers))))))
        n_hits <- vapply(vwhichPDict(pdict, DNAStringSet(normal_df$sequence)),
                         length, integer(1))
        normal_df <- normal_df[n_hits >= 30, ]
    }

    if (nrow(normal_df) == 0) {
        log_msg("  No normal reads at locus — skipping")
        return(NULL)
    }
    log_msg("  ", nrow(normal_df), " normal reads retained")

ERROR: Error in .Call2("ACtree2_build", tb, pp_exclude, base_codes, nodebuf_ptr, : non base DNA letter found in Trusted Band for pattern 2340

In [12]:
all_kmers_normal <- unlist(lapply(
    normal_rough_df$sequence[normal_rough_df$read_ID %in% normal_reads_locus], get_kmers))
kmer_counts   <- table(all_kmers_normal)
contig_normal <- assemble_kmers(names(kmer_counts[kmer_counts >= 10]), k = K)
contig_normal
cat("Contig normal :", nchar(contig_normal[1]), "bp\n")

[1] "ACTTACTCTGGGTCTCTAGGCTTTGGATCCAGCAGCTGCCGCTCCCTGGGCTATGGATCGAGGAGCTGCTACTCAGTGGGCTGTGGGTCCAGTGGCTTCAGATCCCTGGGTTATGGAGGCTGTGGCTTCCCTTCCCTGGGCTATGGCGTTGGATTCTGCCGCCCAACCTACTTGGCTTCTAGGAGCTGCCAGTCTTCTTGCTACAGACCAACTTGTGGATCAGGCTTCTACT"
[2] "AGTAGAAGCCTGATCCACAAGTTGGTCTGTAGCAAGAAGACTGGCAGCTCCTAGAAGCCAAGTAGGTTGGGCGGCAGAATCCAACGCCATAGCCCAGGGAAGGGAAGCCACAGCCTCCATAACCCAGGGATCTGAAGCCACTGGACCCACAGCCCACTGAGTAGCAGCTCCTCGATCCATAGCCCAGGGAGCGGCAGCTGCTGGATCCAAAGCCTAGAGACCCAGAGTAAGT"

Contig normal : 232 bp

In [ ]:
all_kmers_normal <- unlist(lapply(
    normal_reads_df$sequence[normal_reads_df$read_ID %in% normal_reads_locus], get_kmers))
kmer_counts   <- table(all_kmers_normal)
contig_normal <- assemble_kmers(names(kmer_counts[kmer_counts >= 10]), k = K)
contig_normal
cat("Contig normal :", nchar(contig_normal[1]), "bp\n")

### Alignment to retrieve SNV

In [13]:
# Meilleur alignement parmi les 4 orientations
alns <- lapply(list(
    c(contig_normal[1], contig_tumour[1]),
    c(contig_normal[1], contig_tumour[2]),
    c(contig_normal[2], contig_tumour[1]),
    c(contig_normal[2], contig_tumour[2])
), function(x) pairwiseAlignment(
    DNAString(x[1]), DNAString(x[2]), type = "local",
    substitutionMatrix = nucleotideSubstitutionMatrix(match=1, mismatch=-1),
    gapOpening = -5, gapExtension = -2
))
best_aln <- alns[[which.max(sapply(alns, score))]]

# Visualisation
pat  <- strsplit(as.character(pattern(best_aln)), "")[[1]]
sub  <- strsplit(as.character(subject(best_aln)),  "")[[1]]
diff <- ifelse(pat == sub, ".", "*")
cat("Normal :", paste(pat,  collapse=""), "\n")
cat("        ", paste(diff, collapse=""), "\n")
cat("Tumeur :", paste(sub,  collapse=""), "\n")

# SNVs
mm <- mismatchTable(best_aln)

if (nrow(mm) == 0) { cat("Aucune mutation détecté\n"); return(NULL) }
cat(nrow(mm), "Candidate SNV(s) :\n")
for (i in seq_len(nrow(mm))) {
    cat("  ", as.character(mm$PatternSubstring[i]), "->",
              as.character(mm$SubjectSubstring[i]),
        "| position dans contig :", mm$PatternStart[i], "\n")
}

Normal : GGTCCAGTGGCTTCAGATCCCTGGGTTATGGAGGCTGTGGCTTCCCTTCCCTGGGCTATGG
         ..............................*..............................
Tumeur : GGTCCAGTGGCTTCAGATCCCTGGGTTATGAAGGCTGTGGCTTCCCTTCCCTGGGCTATGG
1 Candidate SNV(s) :
   G -> A | position dans contig : 116

In [15]:
germline <- is_germline_fast(mm, contig_normal)
mm_somatic <- mm[!germline, ]
mm_somatic

  PatternId PatternStart PatternEnd PatternSubstring SubjectStart SubjectEnd
1 1         116          116        G                31           31
  SubjectSubstring
1 A

In [88]:
writeLines(c(">contig_normal1", contig_normal[1]), 
           "/srv/home/mlef0011/VDARK/rawdata/contigs/contigs_normal.fa")

minimap2 -ax sr /srv/home/mlef0011/rawdata/ref_genome/reference_genome_GRCh37.fa /srv/home/mlef0011/VDARK/rawdata/contigs/contigs_normal.fa > /srv/home/mlef0011/VDARK/rawdata/contigs/contigs_normal_aln.sam

In [90]:
# --- Lire le SAM ---
sam <- read.table("/srv/home/mlef0011/VDARK/rawdata/contigs/contigs_normal_aln.sam", 
                  sep="\t", comment.char="@", fill=TRUE)
# Flag du read
flag <- sam[1, 2]
is_reverse <- bitwAnd(flag, 16) != 0  # TRUE si brin reverse
is_reverse
chrom <- sam[1, 3]
pos   <- sam[1, 4]  # position de début du contig sur le génome
contig = sam[1, 10]
# --- Boucle sur les mutations détectées ---
# Parser le soft-clip depuis le CIGAR
cigar <- as.character(sam[1, 6])

# Soft-clip gauche (S) ou hard-clip gauche (H)
left_clip <- 0
m <- regmatches(cigar, regexpr("^([0-9]+)[SH]", cigar))
if (length(m) > 0) left_clip <- as.integer(sub("[SH]", "", m))

# Soft-clip droit (S) ou hard-clip droit (H)
right_clip <- 0
m <- regmatches(cigar, regexpr("([0-9]+)[SH]$", cigar))
if (length(m) > 0) right_clip <- as.integer(sub("[SH]", "", m))
for (i in seq_len(nrow(mm_somatic))) {
    
    # Position dans le contig complet (pattern(best_aln) commence après le soft-clip)
    pos_in_contig <- mm_somatic$PatternStart[i]
    
    # Décalage : pos SAM = position génomique de la première base MAPPÉE
    # donc on soustrait le soft-clip pour avoir la position de la base 1 du contig
    pos_mut_genome <- if (is_reverse) {
        pos + nchar(as.character(contig)) - right_clip - pos_in_contig
    } else {
        pos - left_clip + pos_in_contig - 1
    }
    
    snv_ref <- as.character(mm_somatic$PatternSubstring[i])
    snv_alt <- as.character(mm_somatic$SubjectSubstring[i])
    
    if (is_reverse) {
        snv_ref <- as.character(reverseComplement(DNAString(snv_ref)))
        snv_alt <- as.character(reverseComplement(DNAString(snv_alt)))
    }
    
    cat("Chromosome :", as.character(chrom),
        "| Position :", pos_mut_genome,
        "| SNV :", snv_ref, "->", snv_alt, "\n")
}

[1] TRUE

Chromosome : 21 | Position : 10896818 | SNV : G -> C
Chromosome : 21 | Position : 10896817 | SNV : A -> G

## Pipeline for multiple SNVs

In [9]:
cat("Chargement des reads tumeur (tumeur specifique)...\n")
fq_tumour_specific_R1 <- readDNAStringSet("/srv/home/mlef0011/VDARK/rawdata/reads/tumour_R1_tumour_specific.fq", format="fastq")
fq_tumour_specific_R2 <- readDNAStringSet("/srv/home/mlef0011/VDARK/rawdata/reads/tumour_R2_tumour_specific.fq", format="fastq")
tumour_specific_reads_df <- data.frame(
    read_ID  = c(names(fq_tumour_specific_R1), names(fq_tumour_specific_R2)),
    sequence = as.character(c(fq_tumour_specific_R1, fq_tumour_specific_R2)),
    stringsAsFactors = FALSE
)
cat(nrow(tumour_specific_reads_df), "reads tumeur\n")

Chargement des reads tumeur (tumeur specifique)...
52644 reads tumeur

In [37]:
system("/srv/home/mlef0011/anaconda3/condabin/conda run -n VDARK python3 /srv/home/mlef0011/VDARK/src/build_read_kmer_table.py")

In [11]:
# ── Clustering ─────────────────────────────────────────────────────────────────
cat("Read clustering...\n")
read_kmer_df <- fread("/srv/home/mlef0011/VDARK/rawdata/reads/read_kmer_association.tsv")
read_kmer_df <- read_kmer_df[, if (.N <= 50) .SD, by = kmer]  # retirer k-mers trop fréquents

pairs_weighted <- read_kmer_df[, {
    ids <- read_ID
    if (length(ids) >= 2) {
        idx <- combn(length(ids), 2)
        data.table(read_ID.x = ids[idx[1,]], read_ID.y = ids[idx[2,]])
    }
}, by = kmer][, .(weight = .N), by = .(read_ID.x, read_ID.y)]

G <- graph_from_data_frame(pairs_weighted, directed = FALSE)
E(G)$weight <- pairs_weighted$weight
clusters <- components(G)
cat(clusters$no, "clusters\n")

Read clustering...
3235 clusters

In [13]:
SNV_list <- lapply(c(1:5), function(cluster_ID) {

    message("\n========== Cluster ", cluster_ID, " ==========")

    # Get reads and k-mers from cluster
    reads_in_cluster <- names(clusters$membership)[clusters$membership == cluster_ID]

    kmers_in_cluster <- unique(read_kmer_df$kmer[
        read_kmer_df$read_ID %in% reads_in_cluster
    ])

    all_kmers_cluster <- unique(unlist(lapply(
        tumour_specific_reads_df$sequence[
            tumour_specific_reads_df$read_ID %in% reads_in_cluster
        ],
        get_kmers
    )))

    message(length(reads_in_cluster), " reads | ",
            length(kmers_in_cluster), " specific k-mers")

    # Assemble tumour contig
    contig_tumour <- assemble_kmers(kmers_in_cluster, k = K)

    message("Tumour contig: ", nchar(contig_tumour[1]), " bp")


    # ── Extract flanking kmers ─────────────────────────────

    flanking_kmers <- setdiff(all_kmers_cluster, kmers_in_cluster)

    flanking_fa <- paste0("/srv/home/mlef0011/VDARK/tmp/flanking_kmers_", cluster_ID, ".fa")

    writeLines(
        paste0(">kmer_", seq_along(flanking_kmers), "\n", flanking_kmers),
        flanking_fa
    )


    # Build KMC database
    system(paste(
        "/srv/home/mlef0011/VDARK/software/kmc/bin/kmc -k31 -t12 -ci1 -fm",
        flanking_fa,
        paste0("/srv/home/mlef0011/VDARK/tmp/flanking_kmc_", cluster_ID),
        "/srv/home/mlef0011/VDARK/tmp/"
    ))


    # Rough filtering of normal reads
    system(paste(
        "/srv/home/mlef0011/VDARK/software/kmc/bin/kmc_tools filter",
        paste0("/srv/home/mlef0011/VDARK/tmp/flanking_kmc_", cluster_ID), "-ci1",
        "/srv/home/mlef0011/VDARK/rawdata/normal_R1.fq",
        paste0("/srv/home/mlef0011/VDARK/tmp/normal_R1_locus_", cluster_ID, ".fq")
    ))

    system(paste(
        "/srv/home/mlef0011/VDARK/software/kmc/bin/kmc_tools filter",
        paste0("/srv/home/mlef0011/VDARK/tmp/flanking_kmc_", cluster_ID), "-ci1",
        "/srv/home/mlef0011/VDARK/rawdata/normal_R2.fq",
        paste0("/srv/home/mlef0011/VDARK/tmp/normal_R2_locus_", cluster_ID, ".fq")
    ))


    # Load filtered reads
    fq_R1 <- readDNAStringSet(
        paste0("/srv/home/mlef0011/VDARK/tmp/normal_R1_locus_", cluster_ID, ".fq"),
        format = "fastq"
    )

    fq_R2 <- readDNAStringSet(
        paste0("/srv/home/mlef0011/VDARK/tmp/normal_R2_locus_", cluster_ID, ".fq"),
        format = "fastq"
    )

    normal_df <- data.frame(
        read_ID  = c(names(fq_R1), names(fq_R2)),
        sequence = as.character(c(fq_R1, fq_R2)),
        stringsAsFactors = FALSE
    )


    # Precise filtering using flanking k-mers
    pdict <- PDict(unique(c(
        flanking_kmers,
        as.character(reverseComplement(DNAStringSet(flanking_kmers)))
    )))

    n_hits <- vapply(
        vwhichPDict(pdict, DNAStringSet(normal_df$sequence)),
        length,
        integer(1)
    )

    normal_reads <- normal_df$read_ID[n_hits >= 30]
    
    if (length(normal_reads) == 0) {
        message("No normal reads matching flanking kmers")
        return(NULL)
    }
    message(length(normal_reads), " normal reads retained")


    # Assemble normal contig
    all_kmers_normal <- unlist(lapply(
        normal_df$sequence[normal_df$read_ID %in% normal_reads],
        get_kmers
    ))

    kmer_counts <- table(all_kmers_normal)

    contig_normal <- assemble_kmers(
        names(kmer_counts[kmer_counts >= 10]),
        k = K
    )

    message("Normal contig: ", nchar(contig_normal[1]), " bp")


    # ── Align tumour vs normal ─────────────────────────────

    orientations <- list(
        c(contig_normal[1], contig_tumour[1]),
        c(contig_normal[1], contig_tumour[2]),
        c(contig_normal[2], contig_tumour[1]),
        c(contig_normal[2], contig_tumour[2])
    )

    alns <- lapply(orientations, function(x) {
        pairwiseAlignment(
            DNAString(x[1]),
            DNAString(x[2]),
            type = "local",
            substitutionMatrix = nucleotideSubstitutionMatrix(match = 1, mismatch = -1),
            gapOpening = -5,
            gapExtension = -2
        )
    })

    best_aln <- alns[[which.max(sapply(alns, score))]]


    # Display alignment
    pat <- strsplit(as.character(pattern(best_aln)), "")[[1]]
    sub <- strsplit(as.character(subject(best_aln)), "")[[1]]

    diff <- ifelse(pat == sub, ".", "*")

    cat("Normal :", paste(pat, collapse=""), "\n")
    cat("        ", paste(diff, collapse=""), "\n")
    cat("Tumour :", paste(sub, collapse=""), "\n")


    # ── Detect SNVs ─────────────────────────────

    mm <- mismatchTable(best_aln)

    if (nrow(mm) == 0) {
        message("No mutations detected")
        return(NULL)
    }

    germline <- is_germline_fast(mm, contig_normal)

    mm_somatic <- mm[!germline, ]

    if (nrow(mm_somatic) == 0) {
        message("Only germline variants detected")
        return(NULL)
    }

    message(nrow(mm_somatic), " somatic mutation(s) detected")

    return(list(
        cluster_ID = cluster_ID,
        mismatches = mm_somatic,
        contig_tumour = contig_tumour,
        contig_normal = contig_normal
    ))

})

SNV_list <- Filter(Negate(is.null), SNV_list)

message("\n", length(SNV_list), " cluster(s) with SNVs detected\n")

========== Cluster 1 ==========

20 reads | 53 specific k-mers

Tumour contig: 61 bp

52 normal reads retained

Normal contig: 122 bp

Normal : AGCTCTCTAAGACTGCACTACAACCTGTGTGATCCCTATTGCTTCCAGAAATATAA
         ..............................*.........................
Tumour : AGCTCTCTAAGACTGCACTACAACCTGTGTAATCCCTATTGCTTCCAGAAATATAA

1 somatic mutation(s) detected


========== Cluster 2 ==========

18 reads | 31 specific k-mers

Tumour contig: 61 bp

82 normal reads retained

Normal contig: 232 bp

Normal : GGTCCAGTGGCTTCAGATCCCTGGGTTATGGAGGCTGTGGCTTCCCTTCCCTGGGCTATGG
         ..............................*..............................
Tumour : GGTCCAGTGGCTTCAGATCCCTGGGTTATGAAGGCTGTGGCTTCCCTTCCCTGGGCTATGG

1 somatic mutation(s) detected


========== Cluster 3 ==========

5 reads | 2 specific k-mers

Tumour contig: 32 bp

No normal reads matching flanking kmers


========== Cluster 4 ==========

8 reads | 31 specific k-mers

Tumour contig: 61 bp

31 normal reads retained

Normal contig: 143 bp

Normal : ACACACACACACCCCTCAACACACCATGCCCTTTGTCTCTCTTTGTATTCCTCTGGCCAGG
         ..............................*..............................
Tumour : ACACACACACACCCCTCAACACACCATGCCGTTTGTCTCTCTTTGTATTCCTCTGGCCAGG

1 somatic mutation(s) detected


========== Cluster 5 ==========

17 reads | 31 specific k-mers

Tumour contig: 61 bp

59 normal reads retained

Normal contig: 234 bp

Normal : GACAGGACCCTTCTGATGGCAACGTTGGCTGAAGGACCACATGGCATTCTTGTGGAACCTT
         ..............................*..............................
Tumour : GACAGGACCCTTCTGATGGCAACGTTGGCTAAAGGACCACATGGCATTCTTGTGGAACCTT

1 somatic mutation(s) detected


4 cluster(s) with SNVs detected

In [18]:
fasta_contig_normal = "/srv/home/mlef0011/VDARK/rawdata/contigs/contigs_normal.fa"

fasta_lines <- unlist(lapply(SNV_list, function(x) {
    c(paste0(">contig_cluster_", x$cluster_ID),
      x$contig_normal[1])
}))
writeLines(fasta_lines, fasta_contig_normal)

In [19]:
minimap = "/srv/home/mlef0011/anaconda3/envs/VDARK/bin/minimap2"
reference_genome = "/srv/home/mlef0011/rawdata/ref_genome/reference_genome_GRCh37.fa"
alignment_minimap_normal_contig = "/srv/home/mlef0011/VDARK/rawdata/contigs/contigs_normal_aln.sam"
system(paste(minimap,"-ax sr", reference_genome, fasta_contig_normal, ">", alignment_minimap_normal_contig))

In [20]:
# --- Lire le SAM ---
sam <- read.table(alignment_minimap_normal_contig, 
                  sep="\t", comment.char="@", fill=TRUE)
# Flag du read
flag <- sam[1, 2]
is_reverse <- bitwAnd(flag, 16) != 0  # TRUE si brin reverse
is_reverse
chrom <- sam[1, 3]
pos   <- sam[1, 4]  # position de début du contig sur le génome
contig = sam[1, 10]
# --- Boucle sur les mutations détectées ---
# Parser le soft-clip depuis le CIGAR
cigar <- as.character(sam[1, 6])

# Soft-clip gauche (S) ou hard-clip gauche (H)
left_clip <- 0
m <- regmatches(cigar, regexpr("^([0-9]+)[SH]", cigar))
if (length(m) > 0) left_clip <- as.integer(sub("[SH]", "", m))

# Soft-clip droit (S) ou hard-clip droit (H)
right_clip <- 0
m <- regmatches(cigar, regexpr("([0-9]+)[SH]$", cigar))
if (length(m) > 0) right_clip <- as.integer(sub("[SH]", "", m))
for (i in seq_len(nrow(mm_somatic))) {
    
    # Position dans le contig complet (pattern(best_aln) commence après le soft-clip)
    pos_in_contig <- mm_somatic$PatternStart[i]
    
    # Décalage : pos SAM = position génomique de la première base MAPPÉE
    # donc on soustrait le soft-clip pour avoir la position de la base 1 du contig
    pos_mut_genome <- if (is_reverse) {
        pos + nchar(as.character(contig)) - right_clip - pos_in_contig
    } else {
        pos - left_clip + pos_in_contig - 1
    }
    
    snv_ref <- as.character(mm_somatic$PatternSubstring[i])
    snv_alt <- as.character(mm_somatic$SubjectSubstring[i])
    
    if (is_reverse) {
        snv_ref <- as.character(reverseComplement(DNAString(snv_ref)))
        snv_alt <- as.character(reverseComplement(DNAString(snv_alt)))
    }
    
    cat("Chromosome :", as.character(chrom),
        "| Position :", pos_mut_genome,
        "| SNV :", snv_ref, "->", snv_alt, "\n")
}

[1] TRUE

ERROR: Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'nrow': object 'mm_somatic' not found

In [ ]:
sam <- read.table(alignment_minimap_normal_contig, 
                  sep="\t", comment.char="@", fill=TRUE)
# Flag du read
flag <- sam[1, 2]
is_reverse <- bitwAnd(flag, 16) != 0  # TRUE si brin reverse
is_reverse
chrom <- sam[1, 3]
pos   <- sam[1, 4]  # position de début du contig sur le génome
contig = sam[1, 10]
# --- Boucle sur les mutations détectées ---
# Parser le soft-clip depuis le CIGAR
cigar <- as.character(sam[1, 6])

# Soft-clip gauche (S) ou hard-clip gauche (H)
left_clip <- 0
m <- regmatches(cigar, regexpr("^([0-9]+)[SH]", cigar))
if (length(m) > 0) left_clip <- as.integer(sub("[SH]", "", m))

# Soft-clip droit (S) ou hard-clip droit (H)
right_clip <- 0
m <- regmatches(cigar, regexpr("([0-9]+)[SH]$", cigar))
if (length(m) > 0) right_clip <- as.integer(sub("[SH]", "", m))
for (i in seq_len(nrow(mm_somatic))) {
    
    # Position dans le contig complet (pattern(best_aln) commence après le soft-clip)
    pos_in_contig <- mm_somatic$PatternStart[i]
    
    # Décalage : pos SAM = position génomique de la première base MAPPÉE
    # donc on soustrait le soft-clip pour avoir la position de la base 1 du contig
    pos_mut_genome <- if (is_reverse) {
        pos + nchar(as.character(contig)) - right_clip - pos_in_contig
    } else {
        pos - left_clip + pos_in_contig - 1
    }
    
    snv_ref <- as.character(mm_somatic$PatternSubstring[i])
    snv_alt <- as.character(mm_somatic$SubjectSubstring[i])
    
    if (is_reverse) {
        snv_ref <- as.character(reverseComplement(DNAString(snv_ref)))
        snv_alt <- as.character(reverseComplement(DNAString(snv_alt)))
    }
    
    cat("Chromosome :", as.character(chrom),
        "| Position :", pos_mut_genome,
        "| SNV :", snv_ref, "->", snv_alt, "\n")
}

In [22]:
# --- Lire le SAM ---
sam <- read.table("/srv/home/mlef0011/VDARK/rawdata/contigs/contigs_normal_aln.sam", 
                  sep="\t", comment.char="@", fill=TRUE)


for(x in seq_len(length(SNV_list))){
    cat("------------------------\n")
    mm = SNV_list[[x]]$mismatches
    flag <- sam[x, 2]
    is_reverse <- bitwAnd(flag, 16) != 0  # TRUE si brin reverse
    is_reverse
    chrom <- sam[x, 3]
    pos   <- sam[x, 4]  # position de début du contig sur le génome
    contig = sam[x, 10]
    # --- Boucle sur les mutations détectées ---
    # Parser le soft-clip depuis le CIGAR
    cigar <- as.character(sam[x, 6])

    # Soft-clip gauche (S) ou hard-clip gauche (H)
    left_clip <- 0
    m <- regmatches(cigar, regexpr("^([0-9]+)[SH]", cigar))
    if (length(m) > 0) left_clip <- as.integer(sub("[SH]", "", m))

    # Soft-clip droit (S) ou hard-clip droit (H)
    right_clip <- 0
    m <- regmatches(cigar, regexpr("([0-9]+)[SH]$", cigar))
    if (length(m) > 0) right_clip <- as.integer(sub("[SH]", "", m))

    # --- Boucle sur les mutations détectées ---
    for (i in seq_len(nrow(mm))) {

        # Calcul de la position génomique
        pos_mut_genome <- if (is_reverse) {        
            pos + nchar(contig) - mm$PatternStart[i]
        } else {
            pos + mm$PatternStart[i] - 1
        }

        # SNV sur le brin reverse si nécessaire
        snv_ref <- as.character(mm$PatternSubstring[i])
        snv_alt <- as.character(mm$SubjectSubstring[i])

        if (is_reverse) {
            snv_ref <- as.character(reverseComplement(DNAString(snv_ref)))
            snv_alt <- as.character(reverseComplement(DNAString(snv_alt)))
        }

        # Affichage
        cat("Chromosome :", as.character(chrom), 
            "| Position :", pos_mut_genome,
            "| SNV :", snv_ref, "->", snv_alt, "\n")
    }
}

------------------------
Chromosome : 21 | Position : 31442822 | SNV : C -> T
------------------------
Chromosome : 21 | Position : 31768802 | SNV : G -> A
------------------------
Chromosome : 21 | Position : 44593920 | SNV : C -> G
------------------------
Chromosome : 21 | Position : 33221825 | SNV : C -> T

In [36]:
mutations_data = fread("/srv/home/mlef0011/VDARK/rawdata/448fe471-3f4e-4dc8-a4e0-6f147dc93abe.consensus.20160830.somatic.snv_mnv.vcf.gz", header=T, sep = "\t")
mutations_data[mutations_data$`#CHROM`== 21 & mutations_data$POS == 31442822 ,]
mutations_data[mutations_data$`#CHROM`== 21 & mutations_data$POS == 31768802 ,]
mutations_data[mutations_data$`#CHROM`== 21 & mutations_data$POS == 33221825 ,]
mutations_data[mutations_data$`#CHROM`== 21 & mutations_data$POS == 44593920 ,]

  #CHROM POS      ID REF ALT QUAL FILTER
1 21     31442822 .  C   T   .    .
  INFO
1 Callers=broad,dkfz,muse;NumCallers=3;VAF=0.35;t_alt_count=14;t_ref_count=26;Variant_Classification=IGR

  #CHROM POS      ID REF ALT QUAL FILTER
1 21     31768802 .  G   A   .    .
  INFO
1 Callers=broad,dkfz,muse,sanger;NumCallers=4;VAF=0.6667;cosmic=COSM419269;t_alt_count=18;t_ref_count=9;Variant_Classification=Missense_Mutation

  #CHROM POS      ID REF ALT QUAL FILTER
1 21     33221825 .  C   T   .    .
  INFO
1 Callers=broad,dkfz,muse,sanger;NumCallers=4;VAF=0.5385;dbsnp=rs776300076;t_alt_count=14;t_ref_count=12;Variant_Classification=IGR

  #CHROM POS      ID REF ALT QUAL FILTER
1 21     44593920 .  C   G   .    .
  INFO
1 Callers=broad,muse,sanger;NumCallers=3;VAF=0.4706;t_alt_count=8;t_ref_count=9;Variant_Classification=IGR

In [44]:
# =============================================================================
# pipeline.R
# Reference-free somatic SNV detection from tumour/normal WGS data.
#
# Workflow:
#   1. Load tumour-specific reads (pre-filtered by extract_tumor_specific_kmers.sh)
#   2. Build read-kmer association table (Python)
#   3. Cluster reads by shared k-mers
#   4. Per cluster: assemble tumour & normal contigs, align, detect SNVs
#   5. Map normal contigs to reference genome and report genomic coordinates
#
# Prerequisites:
#   - extract_tumor_specific_kmers.sh must have been run
#   - Working directory: /srv/home/mlef0011/VDARK/
# =============================================================================

suppressPackageStartupMessages({
    library(dplyr)
    library(stringr)
    library(Biostrings)
    library(data.table)
    library(igraph)
    library(pwalign)
    library(Rsamtools)
})

source("/srv/home/mlef0011/VDARK/src/utils.r")

WD       <- "/srv/home/mlef0011/VDARK"
MINIMAP  <- "/srv/home/mlef0011/anaconda3/envs/VDARK/bin/minimap2"
REF      <- "/srv/home/mlef0011/rawdata/ref_genome/reference_genome_GRCh37.fa"
N_CORES  <- max(1, detectCores() - 1)

In [45]:
log_msg("Loading tumour-specific reads...")

load_reads <- function(r1, r2) {
    fq1 <- readDNAStringSet(r1, format = "fastq")
    fq2 <- readDNAStringSet(r2, format = "fastq")
    data.frame(
        read_ID  = c(names(fq1), names(fq2)),
        sequence = as.character(c(fq1, fq2)),
        stringsAsFactors = FALSE
    )
}

tumour_reads <- load_reads(
    file.path(WD, "rawdata/reads/tumour_R1_tumour_specific.fq"),
    file.path(WD, "rawdata/reads/tumour_R2_tumour_specific.fq")
)
log_msg(nrow(tumour_reads), " tumour-specific reads")

[17:21:01] Loading tumour-specific reads...

[17:21:01] 52644 tumour-specific reads

In [46]:

log_msg("Building read-kmer table...")
system("/srv/home/mlef0011/anaconda3/condabin/conda run -n VDARK python3 /srv/home/mlef0011/VDARK/src/build_read_kmer_table.py")

[17:21:06] Building read-kmer table...

In [47]:
log_msg("Clustering reads...")

read_kmer_df <- fread(file.path(WD, "rawdata/reads/read_kmer_association.tsv"))
read_kmer_df <- read_kmer_df[, if (.N <= 50) .SD, by = kmer]   # drop high-freq k-mers

pairs <- read_kmer_df[, {
    ids <- read_ID
    if (length(ids) >= 2) {
        idx <- combn(length(ids), 2)
        data.table(read_ID.x = ids[idx[1,]], read_ID.y = ids[idx[2,]])
    }
}, by = kmer][, .(weight = .N), by = .(read_ID.x, read_ID.y)]

G <- graph_from_data_frame(pairs, directed = FALSE)
E(G)$weight <- pairs$weight
clusters <- components(G)
log_msg(clusters$no, " clusters")

[17:21:14] Clustering reads...

[17:21:22] 3235 clusters